// <auto-generated />
using Lab10.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab10.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    [Migration("20250728191551_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab10.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 2,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("Lab10.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "alice@gmail.com",
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Email = "bob@gmail.com",
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Email = "charlie@gmail.com",
                            Name = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Email = "diana@gmail.com",
                            Name = "Diana"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            Email = "ethan@gmail.com",
                            Name = "Ethan"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            Email = "fay@gmail.com",
                            Name = "Fay"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 1,
                            Email = "george@gmail.com",
                            Name = "George"
                        });
                });

            modelBuilder.Entity("Lab10.Models.Employee", b =>
                {
                    b.HasOne("Lab10.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Lab10.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
